name: 'verible-formatter'
description: 'This action formats Verilog/SystemVerilog code'
author: 'Antmicro'
inputs:
  paths:
    description: 'Optional array of paths to directories with source code to format'
    required: false
    default: '.'
  github_token:
    description: 'GITHUB_TOKEN'
    default: ''
runs:
  using: 'docker'
  image: 'docker://ghcr.io/chipsalliance/verible-formatter-action'
