name: Verible formatter example
on: [pull_request, push]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: antmicro/verible-formatter-action@mczyz/break-formatter
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
